server {
        listen       80;
        listen  443 ssl;
        server_name  demo.com www.demo.com;
        #ssl_protocols TLSv1 TLSv1.1 TLSv1.2 SSLv2;
        #ssl_ciphers EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+ECDSA+AES128:EECDH+aRSA+AES128:RSA+AES128:EECDH+ECDSA+AES256:EECDH+aRSA+AES256:RSA+AES256:EECDH+ECDSA+3DES:EECDH+aRSA+3DES:RSA+3DES:!MD5;
        #ssl_prefer_server_ciphers on;
        #ssl_certificate /usr/local/nginx/conf/ssl/demo.com.cer;
        #ssl_certificate_key /usr/local/nginx/conf/ssl/demo.com.key;
        #ssl_session_timeout 5m;
        #ssl_session_cache shared:SSL:10m;
        location / {
                root  html/auto/ldy/demo.com;
                index index.html index.htm;
        }
}

server {
     listen       80;
     listen 443 ;
     server_name  testadd443.com;

     location / {
            root   html/bsfx2;
            index  index.html index.htm;
    }
}


server {
     listen       80;
     server_name  _ ;

     location / {
            root   html/bsfx2;
            index  index.html index.htm;
    }
}

server {
     listen  80 default_server;
     server_name  test2.com ;

     location / {
            root   html/bsfx2;
            index  index.html index.htm;
    }
}

server {
     listen  80 ;
     server_name  test3.com ;

     location / {
            root   html/bsfx2;
            index  index.html index.htm;
    }
}

server {
     listen  443 ssl;
     server_name  test3.com ;

     location / {
            root   html/bsfx2;
            index  index.html index.htm;
    }
}