upstream bi_flask_auth {
        server 127.0.0.1:8080;
        server 127.0.0.1:8964 backup;
}


# 後台白名單驗證
server {
        listen 80;
        server_name ;

        access_log  /var/log/nginx/cloudpay_akali.log;
        error_log /var/log/nginx/cloudpay_akali_error.log;
        client_max_body_size 0;

        # 地端 zabbix 域名監控檢查
        location /healthcheck {
                alias html/health_check/;
                index index.html index.htm index.php;

        }

        location / {

                auth_request /bi/auth;
                proxy_pass http://192.168.22.6;   # cloudpay ingress 位置
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_connect_timeout        150;
                proxy_send_timeout           150;
                proxy_read_timeout           150;
                proxy_buffer_size            128k;
                proxy_buffers                8 128k;
                proxy_busy_buffers_size      128k;
                proxy_temp_file_write_size   128k;

        }

        # 總後台白名單驗證認
        location = /bi/auth {

                # 設定為內部使用
                internal;

                proxy_pass http://bi_flask_auth/bi/auth;  # 代理到本地的 Flask 應用

                # 丟棄請求的內容，僅保留標頭資訊
                proxy_pass_request_body off;
                proxy_set_header Content-Length "";

                # 傳遞認證用的標頭資訊給 Flask （請勿拿掉
                proxy_set_header Host $http_host;
                proxy_set_header X-Original-URI $request_uri;
        }
}